### ISSUE TITLE
comfy economy + s faction plugin is very good

### ISSUE THREAD

**Issue by Hexagonforce12** [Soof4/SFactions#1]
![Screenshot_2024-05-01-02-16-55-97](https://github.com/Soof4/SFactions/assets/109804725/0212b156-2b7c-472c-bc28-e051d222c1bb)
![Screenshot_2024-05-01-02-29-27-24](https://github.com/Soof4/SFactions/assets/109804725/88489d83-612a-4909-9540-ea2405429256)

**Comment by LiteralSoofa** [comment]
I'm glad you like it :)
