### ISSUE TITLE
Add command /faction list and /faction delete,Add a feature if join a faction will get special items from that faction, and if leave the faction, the items of that faction will disappear or be deleted

### ISSUE THREAD

**Issue by Hexagonforce12** [Soof4/SFactions#3]

**Comment by LiteralSoofa** [comment]
list and delete commands are good ideas. but item is not, because people can abuse such feature like:
1. Join a faction
2. Get the items
3. Put the items in a chest
4. Leave the faction
5. Repeat from step 1

**Comment by Hexagonforce12** [comment]
> list and delete commands are good ideas. but item is not, because people can abuse such feature like:
> 
> 1. Join a faction
> 2. Get the items
> 3. Put the items in a chest
> 4. Leave the faction
> 5. Repeat from step 1

Yes, it's the same as the bagger plugin, where people use the command /GB then they create another new account then use /gb, they do that continuously without having to fight the boss

**Comment by LiteralSoofa** [comment]
Added ``list`` and ``delete`` commands in [v2.0.0](https://github.com/Soof4/SFactions/releases/tag/v2.0.0). Sorry about the item idea, i can't add that.

**Comment by Hexagonforce12** [comment]
Ok thx for update
